# Generated by Django 3.1.5 on 2021-02-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150, verbose_name='Name')),
                ('job', models.CharField(max_length=150, verbose_name='Cases')),
                ('image', models.ImageField(default='null', upload_to='regiones', verbose_name='Miniatura')),
                ('state', models.BooleanField(verbose_name='¿Estado?')),
            ],
        ),
    ]
